data:
    dataset: "CELEBA"
    image_size: 64
    channels: 3
    logit_transform: false
    uniform_dequantization: false
    gaussian_dequantization: false
    random_flip: true
    rescaled: true
    num_workers: 4

model:
    type: "simple"
    ema_rate: 0.9999
    ema: True
    var_type: fixedlarge

uvit:
    name: 'uvit'
    img_size: 64
    patch_size: 4
    embed_dim: 512
    depth: 12
    num_heads: 8
    mlp_ratio: 4
    qkv_bias: False
    mlp_time_embed: False
    num_classes: -1

diffusion:
    beta_schedule: linear
    beta_start: 0.0001
    beta_end: 0.02
    num_diffusion_timesteps: 1000

training:
    batch_size: 300
    n_epochs: 1000
    n_iters: 500000
    snapshot_freq: 25
    validation_freq: 20000

sampling:
    batch_size: 100
    last_only: True

optim:
    optimizer: "AdamW"
    lr: 0.0002
    weight_decay: 0.03
    beta1: 0.99
    beta2: 0.99
